# かわいい人の最頻値ベクトルがかわいいと判断したベクトルに含まれるか

In [1]:
# pandasモジュールの読み込み
import pandas as pd
# グラフ描画ライブラリmatplotlibの読み込み
import matplotlib.pyplot as plt
# 数値計算用ライブラリnumpyの読み込み
import numpy as np
# 村上3次元の特徴量データを読み込み
# 引数にindex_col=0を入れなとUnnamed:0が追加されてしまう
# index_colで指定した列をスタートで考えてくれる
df = pd.read_csv('../CSV_DATA/arange_feature_all.csv',index_col=0)
# 欠損値をすべて0に置換
df = df.fillna(0)
# インデックスを振り直す
df = df.reset_index()

In [2]:
murakami_pre_value = df[df['Value_of_murakami']==1]
yoshi_pre_value = df[df['Value_of_yoshi']==1]
murakami_pre_value,yoshi_pre_value = murakami_pre_value.drop(['Nose_shape','Nose_len','index','Value_of_murakami','Value_of_yoshi','Cloth_color','name'],axis=1),yoshi_pre_value.drop(['Nose_shape','Nose_len','index','Value_of_murakami','Value_of_yoshi','Cloth_color','name'],axis=1)
murakami_np_array = np.array(murakami_pre_value)
yoshi_np_array = np.array(yoshi_pre_value)
murakami_mode_array = np.array([1.0,1.0,2.0,3.0,1.0,3.0,2.0,2.0,1.0,3.0,1.0,2.0,1.0,1.0])
yoshi_mode_array = np.array([1.0,1.0,2.0,3.0,2.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0])

def mode_slm(pre_list,mode_list):
    count = 0
    for array in pre_list:
        if np.allclose(array,mode_list):
            count = count+1
    return count

print('村上の最頻値ベクトルでかわいいと評価された人は{0}人'.format(mode_slm(murakami_np_array,murakami_mode_array)))
print('吉井の最頻値ベクトルでかわいいと評価された人は{0}人'.format(mode_slm(yoshi_np_array,yoshi_mode_array)))

村上の最頻値ベクトルでかわいいと評価された人は0人
吉井の最頻値ベクトルでかわいいと評価された人は0人


In [3]:
murakami_not_value = df[df['Value_of_murakami']==0]
yoshi_not_value = df[df['Value_of_yoshi']==0]
murakami_pre_value,yoshi_pre_value = murakami_not_value.drop(['Nose_shape','Nose_len','index','Value_of_murakami','Value_of_yoshi','Cloth_color','name'],axis=1),yoshi_not_value.drop(['Nose_shape','Nose_len','index','Value_of_murakami','Value_of_yoshi','Cloth_color','name'],axis=1)
murakami_np_array = np.array(murakami_pre_value)
yoshi_np_array = np.array(yoshi_pre_value)
murakami_mode_array = np.array([1.0,1.0,2.0,3.0,1.0,3.0,2.0,2.0,1.0,3.0,1.0,2.0,1.0,1.0])
yoshi_mode_array = np.array([1.0,1.0,2.0,3.0,2.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0])

def mode_slm(pre_list,mode_list):
    count = 0
    i = 0
    not_pretty = []
    for array in pre_list:
        if np.allclose(array,mode_list):
            count = count+1
            not_pretty.append(i)
        i = i + 1
    print(not_pretty)
    return count

print('村上の最頻値ベクトルでかわいいと評価された人は{0}人'.format(mode_slm(murakami_np_array,murakami_mode_array)))
print('吉井の最頻値ベクトルでかわいいと評価された人は{0}人'.format(mode_slm(yoshi_np_array,yoshi_mode_array)))

[]
村上の最頻値ベクトルでかわいいと評価された人は0人
[84]
吉井の最頻値ベクトルでかわいいと評価された人は1人


In [4]:
yoshi_np_array[84]

array([1., 1., 2., 3., 2., 3., 2., 1., 1., 2., 1., 1., 1., 1.])

# フィールドワークと画像の違い

In [5]:
df

index             name  Face_shape  Hair_len  Eyelid  Eye_shape  \
0        0          sample1         1.0       1.0     2.0        3.0   
1        1          sample2         1.0       1.0     2.0        3.0   
2        2          sample3         4.0       1.0     2.0        3.0   
3        3         アドリアナ・リマ         1.0       1.0     2.0        3.0   
4        4       アンジェラ・ベイビー         3.0       1.0     2.0        3.0   
5        5    アンジェリーナ・ダニロヴァ         1.0       1.0     2.0        3.0   
6        6          アンハサウェイ         4.0       1.0     2.0        3.0   
7        7           エマストーン         1.0       1.0     2.0        3.0   
8        8           エマワトソン         1.0       1.0     2.0        3.0   
9        9      カーラ・デルヴィーニュ         1.0       1.0     2.0        3.0   
10      10         カーリー・クロス         1.0       2.0     2.0        3.0   
11      11             ガッキー         1.0       2.0     3.0        3.0   
12      12          カミーラ・ベル         1.0       2.0     3.0        5.0   
13      13          ガル・ガドット         4.0       1.0     2.0        3.0   
14      14         キーラナイトレイ         1.0       1.0     2.0        3.0   
15      15           サイベネット         1.0       1.0     2.0        3.0   
16      16      ジェニファーローレンス         1.0       2.0     3.0        4.0   
17      17          ジジハディッド         2.0       1.0     2.0        3.0   
18      18         ジュー・ジンイー         1.0       1.0     2.0        3.0   
19      19  スヴェトラーナ・コドチェンコワ         1.0       1.0     2.0        3.0   
20      20        ダシャ・テゥアラン         1.0       1.0     2.0        3.0   
21      21          ダレノガレ明美         1.0       3.0     2.0        3.0   
22      22       テイラー・スウィフト         1.0       2.0     2.0        3.0   
23      23       ナタリー・ポートマン         1.0       1.0     2.0        0.0   
24      24               ナナ         4.0       1.0     3.0        3.0   
25      25         ニーナ・ドブレフ         1.0       1.0     2.0        3.0   
26      26          ファンビンビン         4.0       1.0     2.0        3.0   
27      27         モニカ・ベルッチ         4.0       1.0     2.0        3.0   
28      28          リザソベラーノ         4.0       1.0     2.0        3.0   
29      29          リリーコリンズ         1.0       1.0     2.0        3.0   
..     ...              ...         ...       ...     ...        ...   
177    177               78         1.0       1.0     2.0        2.0   
178    178               79         1.0       1.0     2.0        1.0   
179    179               80         4.0       1.0     2.0        3.0   
180    180               81         1.0       3.0     3.0        3.0   
181    181               82         4.0       1.0     2.0        3.0   
182    182               83         1.0       3.0     3.0        1.0   
183    183               84         4.0       1.0     1.0        5.0   
184    184               85         5.0       1.0     2.0        3.0   
185    185               86         3.0       2.0     2.0        3.0   
186    186               87         3.0       1.0     2.0        1.0   
187    187               88         4.0       1.0     2.0        3.0   
188    188               89         1.0       1.0     2.0        4.0   
189    189               90         5.0       1.0     3.0        4.0   
190    190               91         1.0       1.0     1.0        3.0   
191    191               92         1.0       2.0     2.0        3.0   
192    192               93         2.0       3.0     0.0        4.0   
193    193               94         2.0       1.0     0.0        1.0   
194    194               95         1.0       1.0     2.0        3.0   
195    195               96         4.0       1.0     3.0        4.0   
196    196               97         5.0       1.0     3.0        2.0   
197    197               98         1.0       1.0     2.0        3.0   
198    198               99         4.0       1.0     2.0        1.0   
199    199              100         4.0       1.0     2.0        5.0   
200    200              101         5.0      

In [6]:
murakami_value_data = df[:49]
yoshi_value_data = df[50:98]
rand_value_data = df[100:206]

In [7]:
murakami_mode_array = np.array([1.0,1.0,2.0,3.0,1.0,3.0,2.0,2.0,1.0,3.0,1.0,2.0,1.0,1.0])
yoshi_mode_array= np.array([1.0,1.0,2.0,3.0,2.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0])

In [8]:
murakami_rand_data = rand_value_data[rand_value_data['Value_of_murakami']==1]
yoshi_rand_data = rand_value_data[rand_value_data['Value_of_yoshi']==1]

In [9]:
murakami_rand_data = murakami_rand_data.drop(['index','name','Nose_shape','Nose_len','Value_of_murakami','Value_of_yoshi','Cloth_color'],axis=1)
yoshi_rand_data = yoshi_rand_data.drop(['index','name','Nose_shape','Nose_len','Value_of_murakami','Value_of_yoshi','Cloth_color'],axis=1)

In [10]:
mode_rand_murakami_list=[]
for key,data in murakami_rand_data.items():
    mode_list = murakami_rand_data[key].value_counts()
    mode_list = mode_list.to_dict()
    mode_rand_murakami_list.append(max(mode_list,key=mode_list.get))
    
mode_rand_yoshi_list=[]
for key,data in yoshi_rand_data.items():
    mode_list = yoshi_rand_data[key].value_counts()
    mode_list = mode_list.to_dict()
    mode_rand_yoshi_list.append(max(mode_list,key=mode_list.get))

In [11]:
mode_rand_murakami_list

[1.0, 1.0, 2.0, 3.0, 2.0, 3.0, 2.0, 1.0, 1.0, 3.0, 1.0, 2.0, 1.0, 1.0]

In [12]:
mode_rand_murakami_list == murakami_mode_array

array([ True,  True,  True,  True, False,  True,  True, False,  True,
        True,  True,  True,  True,  True])

In [13]:
print(mode_rand_murakami_list[5])
print(mode_rand_murakami_list[8])

3.0
1.0


In [14]:
murakami_rand_data.head()

Face_shape  Hair_len  Eyelid  Eye_shape  Nose_bridge  Eyebrows  Lips  \
101         2.0       1.0     0.0        0.0          3.0       3.0   0.0   
104         4.0       1.0     0.0        3.0          3.0       1.0   2.0   
105         0.0       1.0     0.0        0.0          3.0       0.0   0.0   
108         4.0       3.0     2.0        2.0          2.0       1.0   2.0   
109         1.0       3.0     2.0        4.0          2.0       1.0   2.0   

     Mouse  Tears_bag  Dis_eye_brows  Forehead  Barb  Gills  Dis_nose_mouse  
101    1.0        2.0            3.0       1.0   1.0    1.0             1.0  
104    3.0        2.0            3.0       1.0   3.0    1.0             1.0  
105    0.0        2.0            0.0       4.0   1.0    0.0             0.0  
108    2.0        2.0            2.0       1.0   3.0    1.0             1.0  
109    3.0        2.0            2.0       1.0   1.0    1.0             1.0

In [15]:
mode_rand_yoshi_list

[1.0, 1.0, 2.0, 3.0, 2.0, 3.0, 2.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, 1.0]

In [16]:
mode_rand_yoshi_list == yoshi_mode_array

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True])

In [17]:
mode_rand_yoshi_list[-3]

2.0

In [18]:
yoshi_rand_data.head()

Face_shape  Hair_len  Eyelid  Eye_shape  Nose_bridge  Eyebrows  Lips  \
103         0.0       1.0     0.0        0.0          2.0       0.0   0.0   
105         0.0       1.0     0.0        0.0          3.0       0.0   0.0   
107         1.0       1.0     2.0        3.0          3.0       1.0   1.0   
108         4.0       3.0     2.0        2.0          2.0       1.0   2.0   
110         3.0       1.0     2.0        3.0          2.0       3.0   3.0   

     Mouse  Tears_bag  Dis_eye_brows  Forehead  Barb  Gills  Dis_nose_mouse  
103    2.0        2.0            2.0       4.0   1.0    1.0             1.0  
105    0.0        2.0            0.0       4.0   1.0    0.0             0.0  
107    2.0        1.0            2.0       1.0   3.0    0.0             1.0  
108    2.0        2.0            2.0       1.0   3.0    1.0             1.0  
110    3.0        1.0            0.0       2.0   3.0    2.0             0.0